# Generated by Django 4.1.3 on 2022-11-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countryModel',
            fields=[
                ('cname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('population', models.BigIntegerField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='diseaseModel',
            fields=[
                ('diseasecode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pathogen', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='diseaseTypeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'diseasetype',
            },
        ),
        migrations.CreateModel(
            name='doctorModel',
            fields=[
                ('degree', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='publicservantModel',
            fields=[
                ('department', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'publicservant',
            },
        ),
        migrations.CreateModel(
            name='usersModel',
            fields=[
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('cname', models.ForeignKey(db_column='cname', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.countrymodel')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='specializeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.doctormodel')),
                ('specid', models.ForeignKey(db_column='specid', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.diseasetypemodel')),
            ],
            options={
                'db_table': 'specialize',
            },
        ),
        migrations.CreateModel(
            name='recordModel',
            fields=[
                ('totaldeath', models.IntegerField()),
                ('totalpatients', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.ForeignKey(db_column='cname', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.countrymodel')),
                ('diseasecode', models.ForeignKey(db_column='diseasecode', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.diseasemodel')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.publicservantmodel')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.AddField(
            model_name='publicservantmodel',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.usersmodel'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.usersmodel'),
        ),
        migrations.AddField(
            model_name='diseasemodel',
            name='id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.diseasetypemodel'),
        ),
        migrations.CreateModel(
            name='discoverModel',
            fields=[
                ('firstencdate', models.DateField(primary_key=True, serialize=False)),
                ('cname', models.ForeignKey(db_column='cname', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.countrymodel')),
                ('diseasecode', models.ForeignKey(db_column='diseasecode', on_delete=django.db.models.deletion.CASCADE, to='dbsweb.diseasemodel')),
            ],
            options={
                'db_table': 'discover',
            },
        ),
    ]
